### ISSUE TITLE
error at mapping json files of script folder

### ISSUE THREAD

**Issue by srikodali** [manolama/opentsdb-elasticsearch#5]
I am trying to install elasticsearch and in the step of "Add a mapping for each JSON file in the ./scripts folder via: curl -X PUT -d @scripts/tsmeta_mapping.json http:///opentsdb/tsmeta/_mapping curl -X PUT -d @scripts/uidmeta_mapping.json http:///opentsdb/uidmeta/_mapping curl -X PUT -d @scripts/annotation_mapping.json http:///opentsdb/annotation/_mapping", I came to know that the json files are tsmeta_map.json, uidmeta_map.json, annotation_map.json rather than tsmeta_mapping.json, uidmeta_mapping.json, annotation_mapping.json. And after changing this also it is throwing error as "curl: (6) Couldn't resolve host 'opentsdb". Are there any changes in url or am I doing wrong anywhere else. 
Thanks,
Sri.

**Comment by manolama** [comment]
It looks like you didn't put the ES hostname in your curl calls there. 

``curl -X PUT -d .json http:///opentsdb/annotation/_mapping`` should be ``curl -X PUT -d .json http://MYESHOSTURL/opentsdb/annotation/_mapping``
