### ISSUE TITLE
Unable to build opentsdb-elasticsearch

### ISSUE THREAD

**Issue by energie786** [manolama/opentsdb-elasticsearch#6]
Following the instructions, i get the following error:

644  [INFO] ------------------------------------------------------------------------
  645  [INFO] BUILD FAILURE
  646  [INFO] ------------------------------------------------------------------------
  647  [INFO] Total time: 55.073 s
  648  [INFO] Finished at: 2015-10-25T16:33:25-07:00
  649  [INFO] Final Memory: 16M/310M
  650  [INFO] ------------------------------------------------------------------------
  651  [ERROR] Failed to execute goal on project otsdb-elasticsearch: Could not resolve dependencies for project net.opentsdb:otsdb-elasticsearch:jar:2.0.0: Could not find artifact net.opentsdb:opentsdb:jar:2.0.0 in mcaprari-releases (https://github.com/mcaprari/mcaprari-maven-repo/raw/master/releases) -> [Help 1]
  652  [ERROR] 
  653  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
  654  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
  655  [ERROR]

**Comment by lynchlee** [comment]
Hey @energie786 , as we all know, maven will search the jar locally first, so I think you can
1. install the opentsdb jar into you file system with maven;
2. continue your building this plugin.

**Comment by manolama** [comment]
Should be good against master now.
